algorithm: model.MGRD.MGRD
data_path: data/HAI

algorithm_parameters:
    dataset: HAI
    lr: 0.0001
    num_epochs: 20
    batch_size: 64
    anormly_ratio: 2
    d_model: 128
    d_ff: 128
    k: 1
    e_layers: 3
