algorithm: model.MGRD.MGRD
data_path: data/MSL

algorithm_parameters:
    dataset: MSL
    lr: 0.0001
    num_epochs: 20
    batch_size: 128
    anormly_ratio: 10
    d_model: 256
    d_ff: 256
    k: 3
    e_layers: 3
