algorithm: model.MGRD.MGRD
data_path: data/WADI

algorithm_parameters:
    dataset: WADI
    lr: 0.0001
    num_epochs: 20
    batch_size: 256
    anormly_ratio: 10
    d_model: 64
    d_ff: 64
    k: 6
    e_layers: 3
