algorithm: model.MGRD.MGRD
data_path: data/SWaT

algorithm_parameters:
    dataset: SWaT
    lr: 0.0001
    num_epochs: 20
    batch_size: 128
    anormly_ratio: 10
    d_model: 128
    d_ff: 128
    k: 3
    e_layers: 3
