algorithm: model.MGRD.MGRD
data_path: data/SMD

algorithm_parameters:
    dataset: SMD
    lr: 0.0001
    num_epochs: 20
    batch_size: 128
    anormly_ratio: 4
    d_model: 256
    d_ff: 256
    k: 6
    e_layers: 3
