algorithm: model.MGRD.MGRD
data_path: data/SMAP

algorithm_parameters:
    dataset: SMAP
    lr: 0.0001
    num_epochs: 100
    batch_size: 128
    anormly_ratio: 12
    d_model: 32
    d_ff: 32
    k: 6
    e_layers: 3
