algorithm: model.MGRD.MGRD
data_path: data/WADI

algorithm_parameters:
    dataset: WADI
    lr: 0.0001
    num_epochs: 100
    batch_size: 128
    anormly_ratio: 5
    d_model: 256
    d_ff: 256
    k: 1
    e_layers: 3
