algorithm: model.MGRD.MGRD
data_path: data/SWaT

algorithm_parameters:
    dataset: SWaT
    lr: 0.0001
    num_epochs: 100
    batch_size: 32
    anormly_ratio: 12
    d_model: 64
    d_ff: 64
    k: 1
    e_layers: 3
