algorithm: model.MGRD.MGRD
data_path: data/SMD

algorithm_parameters:
    dataset: SMD
    lr: 0.0001
    num_epochs: 100
    batch_size: 256
    anormly_ratio: 4
    d_model: 512
    d_ff: 512
    k: 3
    e_layers: 3
