algorithm: model.MGRD.MGRD
data_path: data/MSL

algorithm_parameters:
    dataset: MSL
    lr: 0.0001
    num_epochs: 100
    batch_size: 32
    anormly_ratio: 10
    d_model: 256
    d_ff: 256
    k: 6
    e_layers: 3
